/**
 * @file tvmrt_types.h
 * @brief Common Type Definitions for TVM Runtime
 * 
 * This header defines shared types used across all runtime modules.
 */

#ifndef TVMRT_TYPES_H_
#define TVMRT_TYPES_H_

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

// ============================================================
// Configuration Limits
// ============================================================

/** Maximum number of input tensors per operator */
#ifndef TVMRT_MAX_OP_INPUTS
#define TVMRT_MAX_OP_INPUTS 4
#endif

/** Maximum number of output tensors per operator */
#ifndef TVMRT_MAX_OP_OUTPUTS
#define TVMRT_MAX_OP_OUTPUTS 2
#endif

/** Maximum number of operators in a model */
#ifndef TVMRT_MAX_OPS
#define TVMRT_MAX_OPS 64
#endif

/** Maximum number of layers in static schedule */
#ifndef TVMRT_MAX_LAYERS
#define TVMRT_MAX_LAYERS 32
#endif

/** Maximum operators per layer */
#ifndef TVMRT_MAX_OPS_PER_LAYER
#define TVMRT_MAX_OPS_PER_LAYER 16
#endif

// ============================================================
// Backend Kind (for heterogeneous scheduling)
// ============================================================

typedef enum {
    TVMRT_BACKEND_CPU = 0,     /**< CPU function pointer */
    TVMRT_BACKEND_NPU = 1,     /**< NPU subgraph (reserved) */
    TVMRT_BACKEND_GPU = 2      /**< GPU kernel (reserved) */
} tvmrt_backend_kind_t;

// ============================================================
// Tensor Memory Mapping
// ============================================================

/**
 * @brief Describes a tensor's memory location within workspace
 * 
 * This is part of the compile-time generated model descriptor.
 */
typedef struct {
    int32_t sid;        /**< Storage ID (from TVM compiler) */
    int32_t offset;     /**< Byte offset in workspace */
    int32_t size;       /**< Size in bytes */
    int32_t align;      /**< Alignment requirement */
} tvmrt_tensor_map_entry_t;

// ============================================================
// Operator Description
// ============================================================

/**
 * @brief Describes an operator in the model graph
 * 
 * Generated by compiler, consumed by semantic layer.
 */
typedef struct {
    int32_t op_id;                               /**< Unique operator ID */
    const char* name;                            /**< Debug name */
    tvmrt_backend_kind_t backend;                /**< Execution backend */
    int32_t func_entry_id;                       /**< Index into function table */
    int32_t input_sids[TVMRT_MAX_OP_INPUTS];     /**< Input tensor SIDs (-1 = unused) */
    int32_t output_sids[TVMRT_MAX_OP_OUTPUTS];   /**< Output tensor SIDs (-1 = unused) */
    int32_t input_count;                         /**< Number of valid inputs */
    int32_t output_count;                        /**< Number of valid outputs */
} tvmrt_op_desc_t;

// ============================================================
// Static Schedule Description
// ============================================================

/**
 * @brief A single layer in BSP schedule (all ops in layer can run in parallel)
 */
typedef struct {
    const int32_t* op_indices;   /**< Array of op IDs to execute */
    int32_t count;               /**< Number of ops in this layer */
} tvmrt_schedule_layer_t;

/**
 * @brief Complete static schedule for a model
 */
typedef struct {
    const tvmrt_schedule_layer_t* layers;  /**< Array of layers */
    int32_t layer_count;                   /**< Number of layers */
} tvmrt_schedule_desc_t;

// ============================================================
// Operator Function Types
// ============================================================

/** Generic operator function signature (for unified dispatch) */
typedef int32_t (*tvmrt_op_func_t)(void* args);

/**
 * @brief Executable operator entry (runtime filled)
 */
typedef struct {
    const char* name;           /**< Debug name */
    tvmrt_op_func_t func;       /**< Function pointer */
    void* args;                 /**< Pre-filled argument struct */
} tvmrt_op_exec_t;

// ============================================================
// Runtime Context
// ============================================================

/**
 * @brief Runtime context for a model instance
 * 
 * This struct holds all state needed for one execution,
 * enabling multiple model instances to run concurrently.
 */
typedef struct {
    uint8_t* workspace;                 /**< Mutable workspace pointer */
    const uint8_t* const_workspace;     /**< Constant data workspace */
    
    tvmrt_op_exec_t* op_execs;          /**< Filled operator entries */
    int32_t op_count;                   /**< Number of operators */
    
    void* args_storage;                 /**< Storage for operator arguments */
} tvmrt_context_t;

#ifdef __cplusplus
}
#endif

#endif  // TVMRT_TYPES_H_
