/**
 * @file tvmrt_semantic.h
 * @brief Semantic Transformation Layer Interface
 * 
 * This layer "parses" compile-time generated descriptors and
 * assembles runtime-executable operator entries.
 * 
 * Aligns with PDF Section 3.1: "语义转换层"
 */

#ifndef TVMRT_SEMANTIC_H_
#define TVMRT_SEMANTIC_H_

#include "tvmrt_types.h"

#ifdef __cplusplus
extern "C" {
#endif

// ============================================================
// Model Descriptor (compile-time generated)
// ============================================================

/**
 * @brief Complete model descriptor generated by compiler
 */
typedef struct {
    const tvmrt_tensor_map_entry_t* tensor_map;  /**< Tensor memory mapping */
    int32_t tensor_count;
    
    const tvmrt_op_desc_t* op_descs;             /**< Operator descriptions */
    int32_t op_count;
    
    const tvmrt_schedule_desc_t* schedule;       /**< Static schedule */
    
    /** Function table for CPU operators */
    const tvmrt_op_func_t* cpu_func_table;
    int32_t cpu_func_count;
} tvmrt_model_desc_t;

// ============================================================
// Semantic Layer API
// ============================================================

/**
 * @brief Initialize runtime context from model descriptor
 * 
 * This function:
 * 1. Resolves tensor SIDs to actual pointers using tensor_map
 * 2. Fills operator argument structures
 * 3. Binds function pointers from function table
 * 
 * @param ctx Runtime context to initialize
 * @param model Model descriptor
 * @param inputs Array of input tensor pointers
 * @param outputs Array of output tensor pointers
 * @param workspace Mutable workspace buffer
 * @param const_workspace Constant data buffer
 * @param op_execs Pre-allocated array for operator entries (size >= model->op_count)
 * @param args_storage Pre-allocated storage for argument structs
 * @return 0 on success, negative on error
 */
int tvmrt_semantic_init(
    tvmrt_context_t* ctx,
    const tvmrt_model_desc_t* model,
    void** inputs,
    void** outputs,
    uint8_t* workspace,
    const uint8_t* const_workspace,
    tvmrt_op_exec_t* op_execs,
    void* args_storage
);

/**
 * @brief Resolve a storage ID to a pointer
 * 
 * @param tensor_map Tensor mapping table
 * @param tensor_count Number of entries in table
 * @param workspace Workspace base pointer
 * @param sid Storage ID to resolve
 * @return Pointer to tensor data, or NULL if not found
 */
void* tvmrt_semantic_resolve_sid(
    const tvmrt_tensor_map_entry_t* tensor_map,
    int32_t tensor_count,
    uint8_t* workspace,
    int32_t sid
);

#ifdef __cplusplus
}
#endif

#endif  // TVMRT_SEMANTIC_H_
