/**
 * @file model_desc.h
 * @brief Model Descriptor Interface
 * 
 * This header provides access to the compile-time generated model descriptor.
 * In a real deployment, this would be auto-generated by the TVM compiler.
 */

#ifndef MODEL_DESC_H_
#define MODEL_DESC_H_

#include "../runtime/tvmrt_types.h"
#include "../runtime/tvmrt_semantic.h"

#ifdef __cplusplus
extern "C" {
#endif

// ============================================================
// Model-specific Constants
// ============================================================

#define MODEL_NUM_TENSORS  5
#define MODEL_NUM_OPS      6
#define MODEL_NUM_LAYERS   4

// ============================================================
// Model Descriptor Access
// ============================================================

/**
 * @brief Get the model descriptor
 * @return Pointer to static model descriptor
 */
const tvmrt_model_desc_t* model_get_descriptor(void);

/**
 * @brief Get tensor map entries
 */
const tvmrt_tensor_map_entry_t* model_get_tensor_map(void);

/**
 * @brief Get operator descriptions
 */
const tvmrt_op_desc_t* model_get_op_descs(void);

/**
 * @brief Get static schedule
 */
const tvmrt_schedule_desc_t* model_get_schedule(void);

// ============================================================
// Argument Structures (model-specific)
// ============================================================

/** Argument structure for single-input fused_add operators */
typedef struct {
    float* p0;          // Input tensor
    float* output;      // Output tensor
    uint8_t* const_ws;  // Constant workspace
    uint8_t* ws;        // Mutable workspace
} FusedAddArgs;

/** Argument structure for dual-input fused_add_3 operator */
typedef struct {
    float* p0;          // First input tensor
    float* p1;          // Second input tensor
    float* output;      // Output tensor
    uint8_t* const_ws;  // Constant workspace
    uint8_t* ws;        // Mutable workspace
} FusedAdd3Args;

// ============================================================
// Model Initialization Helper
// ============================================================

/**
 * @brief Fill operator arguments based on input/output and workspace
 * 
 * This function sets up the args for all operators based on:
 * - External input/output pointers
 * - Resolved workspace SID pointers
 * 
 * @param args Array of argument structures (size >= MODEL_NUM_OPS)
 * @param input External input tensor
 * @param output External output tensor
 * @param workspace Mutable workspace buffer
 * @param const_workspace Constant data buffer
 * @return 0 on success
 */
int model_fill_args(
    void* args,
    float* input,
    float* output,
    uint8_t* workspace,
    const uint8_t* const_workspace
);

#ifdef __cplusplus
}
#endif

#endif  // MODEL_DESC_H_
